'use strict';

/**
 * Build static HTML pages from shared layout + per-page content, and write the
 * two modules the browser shares with the build (the icon set and the image
 * placeholder), so a card rendered client-side is identical to one rendered
 * here. Run with `npm run build`. Output goes to public/.
 */

const fs = require('fs');
const path = require('path');
const { page } = require('../src/site/layout');
const pages = require('../src/site/pages');
const images = require('../src/site/images');
const { ICONS, DESK_ATTRS, MOB_ATTRS } = require('../src/site/icons');

const publicDir = path.join(__dirname, '..', 'public');

/* ---- pages ---- */
let count = 0;
let bytes = 0;
for (const def of pages) {
  const html = page(def);
  const out = path.join(publicDir, def.file);
  // Machine pages live in public/machines/, which may not exist yet.
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, html, 'utf8');
  count += 1;
  bytes += html.length;
  if (!def.file.startsWith('machines/')) console.log(`  built ${def.file} (${html.length} bytes)`);
}
const machinePages = pages.filter((d) => d.file.startsWith('machines/')).length;
console.log(`  built ${machinePages} machine pages in machines/`);
console.log(`[build] wrote ${count} pages (${Math.round(bytes / 1024)} KB)`);

/* ---- the icon set, for cards rendered in the browser ---- */
const iconsJs = `'use strict';
/* Generated by scripts/build-pages.js from src/site/icons.js. Do not edit. */
window.VMAX_ICONS = ${JSON.stringify(ICONS, null, 0)};
window.VMAX_ICON = function (name) {
  var set = window.VMAX_ICONS[name] || window.VMAX_ICONS.machine;
  return '<svg class="ico ico-desk" width="22" height="22" ${DESK_ATTRS} aria-hidden="true">' + set.desk + '</svg>' +
         '<svg class="ico ico-mob" width="20" height="20" ${MOB_ATTRS} aria-hidden="true">' + set.mob + '</svg>';
};
/* Every page carries the sprite, so cards drawn here reference it rather than
   inlining the geometry again. */
window.VMAX_ICON_REF = function (name) {
  var key = window.VMAX_ICONS[name] ? name : 'machine';
  return '<svg class="ico ico-desk" width="22" height="22" aria-hidden="true"><use href="#i-' + key + '-d"/></svg>' +
         '<svg class="ico ico-mob" width="20" height="20" aria-hidden="true"><use href="#i-' + key + '-m"/></svg>';
};
`;
fs.writeFileSync(path.join(publicDir, 'js', 'icons.js'), iconsJs, 'utf8');

/* ---- the image placeholder, so a missing photograph looks the same
        whether the card was built here or drawn in the browser ---- */
const mediaJs = `'use strict';
/* Generated by scripts/build-pages.js from src/site/media.js. Do not edit. */
(function () {
  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }
  function media(img, opts) {
    opts = opts || {};
    var cls = ['media', opts.className || ''].filter(Boolean).join(' ');
    var alt = opts.alt || '';
    if (img && img.src) {
      return '<div class="' + cls + '"><img src="' + esc(img.src) + '" alt="' + esc(alt) +
        '" ' + (opts.eager ? 'fetchpriority="high"' : 'loading="lazy"') + ' decoding="async" /></div>';
    }
    var name = (img && img.name) || 'image';
    var label = (img && img.label) || alt || 'Photograph';
    return '<div class="' + cls + ' is-empty" role="img" aria-label="' + esc(label) +
      ' photograph not uploaded yet: ' + esc(name) + '">' +
      '<span class="media-plate"><span class="media-file">' + esc(name) + '</span>' +
      '<span class="media-hint">' + esc(label) + '</span></span></div>';
  }
  window.VMAX_MEDIA = { media: media, esc: esc };
})();
`;
fs.writeFileSync(path.join(publicDir, 'js', 'media.js'), mediaJs, 'utf8');
console.log('[build] wrote js/icons.js and js/media.js');

/* ---- say out loud what artwork is still outstanding ----
   No photography ships with this site. A deploy running on placeholders is
   meant to be obvious from the build log rather than from the page. */
const { found, missing } = images.report();
if (found.length) console.log(`[build] using ${found.length} supplied image(s): ${found.join(', ')}`);
if (missing.length) {
  console.log(`[build] awaiting ${missing.length} image(s) in public/assets: ${missing.join(', ')}`);
  console.log('[build] each one is drawn as a labelled plate until the file is dropped in.');
}
